version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.3
jobs:
  # create-infrastructure:
  #   docker:
  #     - image: amazon/aws-cli
  #   steps:
  #     - checkout
  #     - run:
  #         name: Create Cloudformation Stack
  #         command: |
  #           aws cloudformation deploy --template-file template.yml --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} --region us-east-1
  configure-infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ['7f:72:b6:cf:f5:57:68:28:63:04:b9:53:be:44:7b:f9']
      - run: apk add --update ansible
      - run:
          name: Configure server
          command: |
            ansible-playbook -i inventory.txt main4.yml
workflows:
  create-infrastructure:
    jobs:
      # - create-infrastructure
      - configure-infrastructure
