version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.3
jobs:
  # create-infrastructure:
  #   docker:
  #     - image: amazon/aws-cli
  #   steps:
  #     - checkout
  #     - run:
  #         name: Create Cloudformation Stack
  #         command: |
  #           aws cloudformation deploy --template-file template.yml --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} --region us-east-1
  configure-infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ['15:19:28:b3:5c:f0:5d:8f:3d:0f:a3:d0:35:bb:68:2b']
          ###### FINGERPRINTS: Ubuntu (pri) above ### before ec2-user
      - run: apk add --update ansible
      - run:
          name: Configure server
          command: |
            ansible-playbook -vvvv -i inventory.txt main.yml
workflows:
  create-infrastructure:
    jobs:
      # - create-infrastructure
      - configure-infrastructure
